version: "3.9"

services:
  flask-app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.app
      FLASK_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
